# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package manifest
COPY package.json package-lock.json ./

# Install dependencies without running scripts (to skip potential issues)
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the project using esbuild
RUN npm run build

# Expose a port if needed (not specified, so omitted)

# Run the MCP server using the built artifact
CMD ["node", "dist/index.cjs"]
